##
# Copyright (C) 2020 Andrew SASSOYE
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as
# published by the Free Software Foundation, version 3.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.
##
sonata_news:
    title:        Ingénu
    link:         https://aees.be
    description:  La revue des ingénieurs
    salt:         'secureToken'
    permalink_generator: sonata.news.permalink.date # sonata.news.permalink.collection
    db_driver:    'doctrine_orm' # doctrine_orm or doctrine_mongodb it is mandatory to choose one here

    comment:
        notification:
            emails:   [email@example.org, email2@example.org]
            from:     no-reply@sonata-project.org
            template: '@SonataNews/Mail/comment_notification.txt.twig'

    class:
        post:       App\Entity\News\Post
        comment:    App\Entity\News\Comment
        media:      App\Entity\Media\Media
        user:       App\Entity\User\User
        tag:        App\Entity\Classification\Tag
        collection: App\Entity\Classification\Collection