##
# Copyright (C) 2020 Andrew SASSOYE
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as
# published by the Free Software Foundation, version 3.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.
##
sonata_page:
    slugify_service: sonata.core.slugify.cocur
    multisite: host_with_path_by_locale
    use_streamed_response: false

    router_auto_register:
        enabled: true
        priority: 150

    ignore_route_patterns:
        - ^(.*)admin(.*)   # ignore admin route, ie route containing 'admin'
        - ^_(.*)          # ignore symfony routes

    ignore_routes:
        - sonata_page_cache_esi
        - sonata_page_cache_ssi
        - sonata_page_js_sync_cache
        - sonata_page_js_async_cache
        - sonata_cache_esi
        - sonata_cache_ssi
        - sonata_cache_js_async
        - sonata_cache_js_sync
        - sonata_cache_apc
        - sonata_media_download

    ignore_uri_patterns:
        - ^\/admin\/   # ignore admin route, ie route containing 'admin'

    default_template: default
    templates:
        default:
            path: 'models/default.html.twig'
            name: 'default'
            containers:
                header:
                    name: Header
                content:
                    name: Contenu
            matrix:
                layout: |

                    HHHHHHHH
                    CCCCCCCC
                    CCCCCCCC

                mapping:
                    H: header
                    C: content
                    F: footer
        col8+4:
            path: 'models/col8+4.html.twig'
            name: 'col8+4'
            containers:
                header:
                    name: Header
                content:
                    name: Contenu
                aside:
                    name: Aside
            matrix:
                layout: |

                    HHHHHHHH
                    CCCCCAAA
                    CCCCCAAA

                mapping:
                    H: header
                    C: content
                    A: aside

        col4+4+4:
            path: 'models/col4+4+4.html.twig'
            name: '3 collones'
            containers:
                header:
                    name: Header
                above:
                    name: Contenu du dessus
                col1:
                    name: Colonne 1
                col2:
                    name: Colonne 2
                col3:
                    name: Colonne 3
                below:
                    name: Contenu du dessous

            matrix:
                layout: |
                    HHHHHHHHH
                    AAAAAAAAA
                    AAAAAAAAA
                    111222333
                    111222333
                    111222333
                    BBBBBBBBB
                    BBBBBBBBB

                mapping:
                    H: header
                    A: above
                    1: col1
                    2: col2
                    3: col3
                    B: below

        col6+6:
            path: 'models/col6+6.html.twig'
            name: '2 colonnes'
            containers:
                header:
                    name: Header

                above:
                    name: Contenu du dessus
                col1:
                    name: Colonne 1
                col2:
                    name: Colonne 2
                below:
                    name: Contenu du dessous
            matrix:
                layout: |

                    HHHHHHHH
                    AAAAAAAA
                    AAAAAAAA
                    11112222
                    11112222
                    11112222
                    BBBBBBBB

                mapping:
                    H: header
                    A: above
                    1: col1
                    2: col2
                    B: below


        homepage:
            path: 'models\homepage.html.twig'
            name: 'homepage'
            containers:
                slider:
                    name: Slider
            matrix:
                layout: |

                    SSSSSSSS

                mapping:
                    S: slider

    direct_publication: '%kernel.debug%'

    catch_exceptions:
        not_found: [404]    # render 404 page with "not_found" key (name generated: _page_internal_error_{key})
        fatal:     [500]    # so you can use the same page for different http errors or specify specific page for each error

    class:
        page: 'App\Entity\Page\Page'
        snapshot: 'App\Entity\Page\Snapshot'
        block: 'App\Entity\Page\Block'
        site: 'App\Entity\Page\Site'
