##
# Copyright (C) 2020 Andrew SASSOYE
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as
# published by the Free Software Foundation, version 3.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.
##
webpack_encore:
    # The path where Encore is building the assets - i.e. Encore.setOutputPath()
    output_path: '%kernel.project_dir%/public/build'
      # If multiple builds are defined (as shown below), you can disable the default build:
      # output_path: false

      # if using Encore.enableIntegrityHashes() and need the crossorigin attribute (default: false, or use 'anonymous' or 'use-credentials')
      # crossorigin: 'anonymous'

      # preload all rendered script and link tags automatically via the http2 Link header
      # preload: true

      # Throw an exception if the entrypoints.json file is missing or an entry is missing from the data
      # strict_mode: false

      # if you have multiple builds:
      # builds:
      # pass "frontend" as the 3rg arg to the Twig functions
      # {{ encore_entry_script_tags('entry1', null, 'frontend') }}

    # frontend: '%kernel.project_dir%/public/frontend/build'

    # Cache the entrypoints.json (rebuild Symfony's cache when entrypoints.json changes)
    # Put in config/packages/prod/webpack_encore.yaml
    # cache: true
