##
# Copyright (C) 2017 Andrew SASSOYE
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as
# published by the Free Software Foundation, version 3.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.
##
imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: services.yml }

    - { resource: assetic.yml }

    # FOS
    - { resource: fos/fos_user.yml }

    - { resource: ivory/ivory_ck_editor.yml }


    # SONATA CORE BUNDLES
    - { resource: sonata/sonata_core.yml }
    - { resource: sonata/sonata_block.yml }
    - { resource: sonata/sonata_user.yml }
    - { resource: sonata/sonata_seo.yml }
    #- { resource: sonata/sonata_cache.yml }
    - { resource: sonata/sonata_page.yml }
    - { resource: sonata/sonata_admin.yml }
    - { resource: sonata/sonata_formatter.yml }
    - { resource: sonata/sonata_media.yml }
    - { resource: sonata/sonata_news.yml }

    - { resource: doctrine_extensions.yml }


# Put parameters here that don't need to change on each machine where the app is deployed
# http://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    locale: fr_FR

framework:
    #esi:             ~
    translator:      { fallbacks: [fr] }
    secret:          "%secret%"
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: ~
    form:            ~
    csrf_protection: ~
    validation:      { enable_annotations: true }
    #serializer:      { enable_annotations: true }
    templating:
        engines: ['twig']
    default_locale:  "%locale%"
    trusted_hosts:   ['jobinge.be', 'aees.be']
    trusted_proxies: ['151.80.44.187']
    session:
        #cookie_domain: '.aees.be'
        cookie_lifetime: 0
        # handler_id set to null will use default session handler from php.ini
        handler_id: Symfony\Component\HttpFoundation\Session\Storage\Handler\PdoSessionHandler

    fragments:       ~
    http_method_override: true
    #profiler:
    #   matcher:
    #        ips: ['91.182.124.30', '2a02:a03f:427a:c800:411:6acc:4ba3:aa70']

# Twig Configuration
twig:
    debug:            "%kernel.debug%"
    strict_variables: "%kernel.debug%"
    form_themes:
        - 'bootstrap_4_layout.html.twig'
        - 'SonataMediaBundle:Form:media_widgets.html.twig'

# Doctrine Configuration
doctrine:
    dbal:
        driver:   pdo_mysql
        host:     "%database_host%"
        port:     "%database_port%"
        dbname:   "%database_name%"
        user:     "%database_user%"
        password: "%database_password%"
        charset:  UTF8
        # if using pdo_sqlite as your database driver:
        #   1. add the path in parameters.yml
        #     e.g. database_path: "%kernel.root_dir%/data/data.db3"
        #   2. Uncomment database_path in parameters.yml.dist
        #   3. Uncomment next line:
        #path:     "%database_path%"

    orm:
        auto_generate_proxy_classes: "%kernel.debug%"
        naming_strategy: doctrine.orm.naming_strategy.underscore
        auto_mapping: true

# Swiftmailer Configuration
swiftmailer:
    transport: "%mailer_transport%"
    host:      "%mailer_host%"
    username:  "%mailer_user%"
    password:  "%mailer_password%"
    encryption: ssl
    auth_mode: plain
