##
# Copyright (C) 2017 Andrew SASSOYE
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as
# published by the Free Software Foundation, version 3.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.
##
# Twig Configuration
twig:
    debug:            "%kernel.debug%"
    strict_variables: "%kernel.debug%"

    #Sonata with Symfony >= 2.6
    form_themes:
        - '@SonataFormatter/Form/formatter.html.twig'

    #Sonata with Symfony <=2.5
    #form:
    #    resources:
    #        - 'SonataFormatterBundle:Form:formatter.html.twig'


sonata_formatter:
    formatters:


        richhtml:
            service: sonata.formatter.text.raw
            extensions:
                - sonata.formatter.twig.control_flow
                - sonata.formatter.twig.gist
                - sonata.media.formatter.twig

        markdown:
            service: sonata.formatter.text.markdown
            extensions:
                - sonata.formatter.twig.control_flow
                - sonata.formatter.twig.gist
                - sonata.media.formatter.twig

        text:
            service: sonata.formatter.text.text
            extensions:
                - sonata.formatter.twig.control_flow
                - sonata.formatter.twig.gist
                - sonata.media.formatter.twig
        #rawhtml:
        #    service: sonata.formatter.text.raw
        #    extensions:
        #        - sonata.formatter.twig.control_flow
        #        - sonata.formatter.twig.gist
        #        - sonata.media.formatter.twig









